### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by cynthiamah** [LocalGround/localground#199]
Wish - Icon for add layer - use icon that has layers with a plus sign. 

Include "add marker" icon to the message "Add places to this dataset by placing markers (icon) on the map.

Can't edit layer name by selecting layer.  Hand appears when I hover, but can't select the layer name.  Works fine from the menu.

Styled by individual - if I delete an item, it becomes listed as "No matches"

Placing marker:  Make the first marker experience consistent.  Icon is a teardrop shape.  I drag a salmon colored teardrop shape.  Current default marker is blue circle.  
Proposal:
1.  When user elects to place a point, use the same + symbol at the cursor that is used in the polyline and polygon commands. 
2.  To be consistent with the icon, make the default point icon the tear drop shape.  Default color - Local Ground teal or current blue.

Add layer:  The default behavior is "Use existing project dataset".  This makes sense if user is making a new map from existing project data.  If they are authoring new data, the logical default is to create a new dataset.  
Proposal:  Default to Create a New Dataset

Layer Properties:  Categorical - If I add something that is out of range, it goes to uncategorized.  The icon used ignores current shape settings for the icon; it uses a circle (color and outline width are used properly).  If I go to layer properties and select categorical again, it re-buckets the categories,  BUT turns all icons to a circle. (Again - outline and color are remembered properly).

Layer Order:  When I add a new layer, it appears at the bottom of the list.  When I refresh, newest layer is on top.  Sort order for layers should be oldest first (unless user has changed layer order - then is should be whatever user has defined).

Layer Information:  Category count is not updated properly.  The count does not update when I add a new item.  

Get rid of Delete / Save Map buttons at bottom of left panel.

Data table still has tabs for photos, audio and video

Riley
Layer Properties uniform - If I create a layer using an existing dataset, the marker icon properties don't match default settings that marker icons were given when layer was created.

Layer Properties/Marker preview - the color of the icon updates but not the shape.  Should be an accurate preview of current shape / color and size.

Layer Properties:  The label Style: has the word "true" following it.  Remove "true"

Layer Properties:  Currently have to select the paintbrush to change the icon style.  Can you make the both the paintbrush and the marker icon selectable?

Layer Properties:  Color Ramp - if I select the down arrow icon, nothing happens.  I have to select the color ramp.  Can you make both the down arrow and the color ramp selectable? 

Layer Properties:  When I switch from Uniform to Individual (the very first time) it changes all the icons from current style to a new style (changed back to a circle of a different color).  The first time Individual is selected, it should take the current properties of Uniform as the default settings.  Use case:  Uniform is the default.  User sets up markers as desired, but then wants to make one item different.  It has changed everything and I have to reset.

Layer Properties: Changing between styled by types:  Can settings for each style be remembered individually so that if I swap between them, they remember the settings for each style?  Settings should be remembered for least the current session. Google My Maps remembers them between sessions.  Use Case:  User sets styled by to Individual.  Modifies a bunch of different icons.  For some reason changes to Uniform but decides they preferred all the things they had set for individual.  Immediately switches back to individual.  Everything is reset.   Oops - no undo for that experiment.

Layer Properties:  If I choose to style by a data column, suggest a logical grouping type.  IE:  My data type is an integer, we should suggest grouping by continuous (ranges).

Layer Properties / Styled By: Swap term Continuous with Ranges.  I think that ranges is more understandable to the lay user.  This is the term used by Google My Maps.  

Layer Properties:  Opacity - change to percentage (i.e. 50% instead of .5)

Layer Properties:  Uniform.  If I select the pencil icon on the "All Items" category and update the icon properties, they are not reflected in the Layer Properties dialog.   Uniform is an odd case where the All Items category icon properties and the Layer Properties icon properties should be coordinated.

**Comment by vanwars** [comment]
@cynthiamah - Is this Issue redundant to 200 + 201?
