### ISSUE TITLE
Remove "Remove location marker" from the item data card

### ISSUE THREAD

**Issue by cynthiamah** [LocalGround/localground#226]
To do item from wrap up meeting 8/20/18

Remove "Remove location marker" button from the item data card

Reasoning:
This command should rarely (if ever) be used.  It is currently in a very prominent place on the item data card.  The user can still remove the marker for an item (but keep it's data record), in the data table view.

**Comment by vanwars** [comment]
Agreed. If there's no marker, there should be an add marker. But if they want to remove the marker, they can do it in the spreadsheet.
