### ISSUE TITLE
Reorganize the "Profile" section

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#29]
As discussed, make the following changes:
- _Left-hand panel_: Menu items are Profile, Projects, Tables, and Snapshots
- Given the left-hand panel selection, allow the user to select between the following media types to batch view / edit: Photos, Audio, Video (Links), Map Images, Prints, and Map Tiles.

A few notes:
- Video isn't fully implemented yet, but don't worry about that for now.
- Attachments needs be deprecated (underway), so ignore that one.
- Forms will be replaced with Tables (and the corresponding spreadsheet interface). Accessible via /profile/tables

**Comment by stlim0730** [comment]
I pushed my branch "profile".
This update is about data filtering feature using projects and 6 media types (tiles are not supported for now).
Snapshot is (temporarily?) removed.
Form simply links to an empty configuration page.

**Comment by vanwars** [comment]
Thanks, Taek. Can you please make a pull request?
