### ISSUE TITLE
Turn on SSL on Local Ground

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#31]
SSL needs to be turned on. Some things to make sure to include with this:
* Procuring a signed certificate
* Ensuring that all hard-coded references to http://* in HTML files are updated to //* (so that there's no mixing between hardcoded and non-hard coded files / fewer redirects are needed)
* updating the deploy_tools/apache_localground_config file to enable SSL (is this necessary?)

**Comment by vibhorev** [comment]
Steps for enabling SSL:
1.	Activate the SSL Module
•	sudo a2enmod ssl
•	sudo service apache2 restart
2.	Create a self-signed SSL certificate [Not needed anymore]
•	Instructions for self-signing here [Not needed anymore]: https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04
3.	Install the purchased version  
•	copy /etc/apache2/ssl.key and /etc/apache2/ssl.crt to the same location on production server 
4.	Make changes to the apache config file (look at /etc/apache2/sites-available/ssl-test.conf)
<VirtualHost *:80>
     ServerName ssl.localground.org
     Redirect "/" "https://ssl.localground.org"
</VirtualHost>
<IfModule mod_ssl.c>
   <VirtualHost *:443>
        SSLEngine on
        SSLCertificateKeyFile /etc/apache2/ssl.key/localground.key
        SSLCertificateFile /etc/apache2/ssl.crt/STAR_localground_org.crt
        SSLCertificateChainFile /etc/apache2/ssl.crt/STAR_localground_org.ca-bundle
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                        SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                        SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                        nokeepalive ssl-unclean-shutdown \
                        downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
   </VirtualHost>
</IfModule>

**Comment by vanwars** [comment]
I'm going to go ahead and close this (fixed with #33).
