### ISSUE TITLE
Reset password form broken

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#41]
Currently, if you navigate to...

https://dev.localground.org/accounts/login/

...and click the "reset password" link, it throws an error. I think it's something small, but needs to be looked into.

**Comment by awesomescot** [comment]
https://github.com/LocalGround/localground/pull/62
Someone should probably test that it's working as expected.  It seems to work to me, but I didn't receive the email, although I'm thinking that's probably an issue with my dev email setup.

**Comment by awesomescot** [comment]
@vanwars I've updated the PR with a fix for the error you were describing.  I'm not exactly sure what I'm doing here, so I don't know that it is the best solution...

**Comment by awesomescot** [comment]
THis has been fixed.
