### ISSUE TITLE
look into using sendgrid to send emails from app

### ISSUE THREAD

**Issue by awesomescot** [LocalGround/localground#42]
Sendgrid has a free offering that might work well for us.  Let's see how much work it would be to integrate this into our app.

**Comment by awesomescot** [comment]
https://github.com/LocalGround/localground/pull/63

**Comment by awesomescot** [comment]
@vanwars What was the issue you were experiencing?  I can't find it in slack.  I think you were saying that the reset password wasn't working, but signing up was working.  I'll check to see if there is a different place where is sends the reset password emails.

**Comment by vanwars** [comment]
Yes. Exactly.

**Comment by awesomescot** [comment]
I'm assuming you were using the password-reset branch?  Or was it the sendgrid branch?  Well it seems as though reset password is broken on both of them.  I think I fixed the reset password link in the email, but then broke it sending the email.  This is more of a reset password bug though.  Did you say you were getting a success response, but no email?

**Comment by awesomescot** [comment]
Ok, so I've pushed a fix where all reset password functionality is there... hopefully.  I just was able to reset my password, got the email, and the link worked.  So please test on the password-reset branch, which as both the sendgrid stuff and reset password fixes.

**Comment by awesomescot** [comment]
This is complete.
