### ISSUE TITLE
migrate db from dev to do box

### ISSUE THREAD

**Issue by awesomescot** [LocalGround/localground#44]
migrate the db over to the new DO box.  Also change password.

**Comment by awesomescot** [comment]
@vanwars Do you know what user the application uses to connect to the db?  I can easily reset the postgres users password, just not sure if anything other than the backup script is using it.

Also I've setup the new backups under the user vanwars, because it was using your ssh key to scp to the topaz server anyway.

**Comment by awesomescot** [comment]
Look in here for app creds:  /localground/apps/settings_local.py

I'll create another user for the app to use.

**Comment by awesomescot** [comment]
@vanwars do you know what database the app should be using in DO?  Right now it's using lg_test_database, is that correct?

**Comment by awesomescot** [comment]
Here is how I created a new user with access to that db.

postgres=# CREATE USER localground WITH PASSWORD '********';
CREATE ROLE
postgres=# GRANT ALL PRIVILEGES ON DATABASE lg_test_database to localground;
GRANT

**Comment by vanwars** [comment]
Let's take this convo to slack..

**Comment by awesomescot** [comment]
I think I have everything setup correctly now.  @vanwars feel free to checkout do.localground.org and let me know if there are any issues.

**Comment by awesomescot** [comment]
@vanwars we should try to close out this ticket.  Let me know if you want to sit down briefly with you and we can finalize this.

**Comment by awesomescot** [comment]
This has been completed.
