### ISSUE TITLE
Implement Data Download

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#56]
We need to add some additional renderers to the REST API in order to support different data download formats (so people can get their data back out of Local Ground). 
### Formats

The following formats need to be supported (in order of priority) for projects, photos, audio, markers, and map images:
1. CSV
2. KML
3. Zip File (should have CSV, metadata, and all source media)
4. KMZ
5. Shapefile (GIS format)
### Endpoints for which data download is needed
- Photos: /api/0/photos/ **[all renderers]**
- Audio: /api/0/audio/ **[everything]**
- Map Images: /api/0/map-images/ **[everything]**
- Markers: /api/0/markers/ **[CSV, KML...markers have complicated nesting. Hold off on Zip]**
- Table Records: /api/0/form/{{id}}/ **[everything]**
- Project: /api/0/projects/{{id}}/ **[just KML, Zip, and KMZ, since projects contain nested data]**
### Notes on the Zip file specs

The zip renderer needs to include the following (using Photo endpoint as an example, but applies to all):
1. Spreadsheet of photos, in CSV format (based on user's query). This spreadsheet should include *local file paths to binaries.
2. Binaries of all photos (based on user's query)

**Comment by stlim0730** [comment]
@vanwars What if a datapoint doesn't have coordinates; uploaded but not mapped? I'm assuming that we don't want to export that kind of data in any formats.

**Comment by vanwars** [comment]
I think non-spatial formats like Excel would be fine, but not KML / KMZ.
