### ISSUE TITLE
User permissions for testing on DO server

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#72]
Hey Scot,

Whenever you get a chance, can you take a look at file permissions for running tests on the DO server. Whenever I try and run the tests, ones that require file read/write from disk throw permissions errors. To recreate:

```shell
cd /localground/apps
sudo -u www-data python manage.py test #running as apache2 user
```

I'm sure it's a quick fix, but you're more knowledgeable that I re: these kinds of things. Also, after you fix the problem, can you also verify that you can still upload files using this form:
https://dev.localground.org/upload/

**Comment by awesomescot** [comment]
I think I've fixed the issue, but I'm unable to login to the site right now, because I forget my username, and there is no sendgrid api key on the server.

**Comment by vanwars** [comment]
There is a sendgrid api key on the server. I added it myself. What error
message are you getting?

**Comment by vanwars** [comment]
This should work: https://dev.localground.org/accounts/password/reset/

**Comment by awesomescot** [comment]
Ah, you are right there is an api key in settings_local.py, I was looking in settings.py.  I'm not getting an email for some reason.

**Comment by vanwars** [comment]
Hmmm. You're in the database. Weird:

lg_dev=# select username, email, is_active from auth_user where username
like '%awesome%'
  username   |         email          | is_active
-------------+------------------------+-----------
 awesomescot | scot.spinner@gmail.com | t
(1 row)

**Comment by awesomescot** [comment]
Ok, tested upload and it seems to work.  Closing this ticket.  I've also added the permissions change to the deploy script.

**Comment by vanwars** [comment]
Yes. Verified that upload works and tests run. Thanks!
