### ISSUE TITLE
Wire up map processor with Celery

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#73]
Map image processing is now working again, and the next step is to wire it up to Celery. Make sure that you've installed the updated libraries (relatively newly added directives)...
```shell
$ sudo apt-get -y install openjdk-7-jre
$ sudo pip install numpy==1.8
```
...and then: generate a print, print it out, draw on it with colored markers, scan it, and upload it using either the API endpoint or using http://localhost:7777/upload/map-images/. Then, you'll need the celery script to call /localground/apps/lib/jobs/process-maps.py (which you can also run manually as follows)...
```shell
$ vagrant ssh
$ cd /localground/apps/lib/jobs/
$ python process-maps.py 
```

**Comment by awesomescot** [comment]
So this was easier than I thought it would be.  This is just the very basic setup of using the celery process worker to process maps.  I think there are a lot of features that we aren't taking advantage of, but I think a lot of those have been programmed in, so maybe we don't need to use them for this instance.
https://github.com/LocalGround/localground/pull/75

**Comment by awesomescot** [comment]
This is complete.  closing.
