### ISSUE TITLE
Object-Level Permissions

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#88]
We need to ensure that all of the media files are enforcing object level security. Please add checks to all objects in data API to ensure that users can't view/edit objects for which they do not have permissions. Each model has a `can_view`, `can_edit`, and `can_manage` method (taking a User as an argument). The API needs to make a call to these methods before fulfilling the request. We really need some thorough tests for this as well.

In addition, it would be really helpful, in the UI, if all of the model serializers had a read_only flag (T/F), so not everything appears editable.

**Comment by tap2k** [comment]
It looks like BaseMedia already is implementing checks for can_edit and can_view that is based on project-level security assignments, but not can_manage.

**Comment by vanwars** [comment]
Great! Can you write some tests for this?

**Comment by tap2k** [comment]
will do - but should these be tests on the model, or through the API? it seems we dont many of the former in apps/site/tests/models.

**Comment by tap2k** [comment]
also - im assuming I should provide an implementation for can_manage?

**Comment by vanwars** [comment]
Tests on API endpoints would be great! And yes, can_manage.

**Comment by tap2k** [comment]
are you on slack? my vagrant install is hanging on "sudo supervisorctl restart celery".

do I need to do something new?
