### ISSUE TITLE
Serving Images

### ISSUE THREAD

**Issue by vanwars** [LocalGround/localground#89]
1. Get rid of Base64 Encode / Decode
2. All media should go in single directory with obscure, machine-generated names.
3. We need to track more metadata for our media files to know both the file dimensions as well as the size, so that we can do quotas.
4. We need to make an export script that generates zip files programmatically.

**Comment by vanwars** [comment]
In the short term, let's just edit the /apps/site/views/mediaserver.py to return media.

**Comment by newdayhost** [comment]
thinking about:
https://github.com/miguelramos/django-media-manager
